# Generated by Django 3.2.7 on 2021-10-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company name')),
                ('position', models.CharField(max_length=200, verbose_name='Position title')),
                ('description', models.CharField(max_length=2500, verbose_name='Job description')),
                ('salary', models.FloatField()),
                ('experience', models.FloatField(verbose_name='Number of year experiences')),
                ('dep', models.CharField(max_length=2, verbose_name='Departement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Compagnies',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Candidate name')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='', verbose_name='CV')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
            ],
        ),
    ]
